### ISSUE TITLE
gamboost learner does not properly specify that it can only do binary classif

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3learners#56] opened 2019-11-28 20:26 UTC
ll = lrn("classif.gamboost")
tt = tsk("iris")
rr = resample(tt, ll, rsmp("cv", folds = 2))

--> results in

INFO  [21:26:36.247] Applying learner 'classif.gamboost' on task 'iris
' (iter 1/2)
Error in family@check_y(y) :
  response is not a factor at two levels but 'family = Binomial()'

shouldt there be an autotest that makes sure that stuff like this does not happen?

**Comment by be-marc** [comment] 2019-11-29 16:26
I cannot reproduce this behavior. I get `Error: Learner 'classif.gamboost' must have the properties: multiclass`. This check is included in `autotest`.

**Comment by mllg** [comment] 2021-08-13 09:02
Fixed via https://github.com/mlr-org/mlr3/commit/ad005bdb5e911a4e7fb568912786246b1d22cece.

**Closed by mllg** 2021-08-13 09:02 UTC
